from __future__ import annotations

import argparse
import importlib
import inspect
import json
from pathlib import Path
import pkgutil
import sys
from types import UnionType
from typing import Annotated, Union, get_args, get_origin

import msgspec

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from structures import build_release_manifest
from structures.base import Structure
from structures.resources.base import ResourceDocument


def write_ts_manifest_module(payload: dict[str, object], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload_json = msgspec.json.format(msgspec.json.encode(payload), indent=2).decode("utf-8")
    module = (
        "/* This file is auto-generated by scripts/export_structures.py. */\n"
        "/* Do not edit manually. */\n"
        "import type { ControlPlaneManifest } from \"../types/controlPlane\";\n\n"
        f"export const controlPlaneManifest = {payload_json} as const satisfies ControlPlaneManifest;\n\n"
        "export type ControlPlaneResourceSchema = ControlPlaneManifest[\"resources\"][number];\n"
        "export type ControlPlaneTableSchema = ControlPlaneManifest[\"tables\"][number];\n\n"
        "export const resourceByKind: Record<string, ControlPlaneResourceSchema> = Object.fromEntries(\n"
        "  controlPlaneManifest.resources.map((resource) => [resource.kind, resource]),\n"
        ") as Record<string, ControlPlaneResourceSchema>;\n\n"
        "export const tableByKind: Record<string, ControlPlaneTableSchema> = Object.fromEntries(\n"
        "  controlPlaneManifest.tables.map((table) => [table.kind, table]),\n"
        ") as Record<string, ControlPlaneTableSchema>;\n"
    )
    output_path.write_text(module, encoding="utf-8")


def _type_label(annotation: object) -> str:
    origin = get_origin(annotation)

    if origin is Annotated:
        return _type_label(get_args(annotation)[0])

    if origin is list:
        args = get_args(annotation)
        inner = _type_label(args[0]) if args else "unknown"
        return f"list[{inner}]"

    if origin in (UnionType, Union):
        values = [_type_label(value) for value in get_args(annotation)]
        return " | ".join(values)

    if str(origin).endswith("Literal"):
        values = ", ".join(repr(value) for value in get_args(annotation))
        return f"Literal[{values}]"

    if origin is dict:
        args = get_args(annotation)
        if len(args) == 2:
            return f"dict[{_type_label(args[0])}, {_type_label(args[1])}]"
        return "dict"

    if origin is tuple:
        args = get_args(annotation)
        if args:
            return "tuple[" + ", ".join(_type_label(value) for value in args) + "]"
        return "tuple"

    if annotation is type(None):
        return "None"
    if isinstance(annotation, type):
        return annotation.__name__
    if origin is not None:
        return getattr(origin, "__name__", str(origin))
    return str(annotation)


def _escape_markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _json_safe(value: object) -> object:
    if isinstance(value, msgspec.Struct):
        return msgspec.to_builtins(value)
    if isinstance(value, list):
        return [_json_safe(item) for item in value]
    if isinstance(value, tuple):
        return [_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    return value


def _stringify_default(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (bool, int, float)) or value is None:
        return json.dumps(value)
    if isinstance(value, (list, dict, tuple)):
        return json.dumps(_json_safe(value), ensure_ascii=False)
    if isinstance(value, msgspec.Struct):
        payload = msgspec.to_builtins(value)
        text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        return text if len(text) <= 96 else text[:93] + "..."
    return repr(value)


def _field_default(field: msgspec.structs.FieldInfo) -> str:
    if field.default is not msgspec.NODEFAULT:
        return _stringify_default(field.default)
    if field.default_factory is not msgspec.NODEFAULT:
        try:
            value = field.default_factory()
        except Exception:
            return "(factory)"
        return _stringify_default(value)
    return ""


def _module_doc_name(module_name: str) -> str:
    return module_name.replace(".", "_") + ".md"


def _discover_structure_modules() -> list[str]:
    modules = {"structures.common"}
    resources_pkg = importlib.import_module("structures.resources")
    for item in pkgutil.walk_packages(resources_pkg.__path__, resources_pkg.__name__ + "."):
        if item.name.endswith(".manifest.generator"):
            continue
        modules.add(item.name)
    return sorted(modules)


def _discover_structures() -> list[tuple[str, list[type[Structure]]]]:
    discovered: list[tuple[str, list[type[Structure]]]] = []
    for module_name in _discover_structure_modules():
        module = importlib.import_module(module_name)
        classes: list[type[Structure]] = []
        for _, candidate in inspect.getmembers(module, inspect.isclass):
            if candidate.__module__ != module_name:
                continue
            if candidate in {Structure, ResourceDocument}:
                continue
            if not issubclass(candidate, Structure):
                continue
            kind = getattr(candidate, "kind", "")
            if not isinstance(kind, str) or not kind:
                continue
            classes.append(candidate)
        if classes:
            discovered.append((module_name, sorted(classes, key=lambda item: item.__name__)))
    return discovered


def _render_structure_section(struct_type: type[Structure]) -> str:
    cfg = struct_type.__struct_config__
    lines = [f"## `{struct_type.kind}`", "", f"- Python type: `{struct_type.__module__}.{struct_type.__name__}`"]
    if cfg.tag_field:
        lines.append(f"- Tag field: `{cfg.tag_field}`")
    if cfg.tag:
        lines.append(f"- Tag value: `{cfg.tag}`")

    fields = msgspec.structs.fields(struct_type)
    if not fields:
        lines.extend(["", "_No fields._", ""])
        return "\n".join(lines)

    lines.extend(
        [
            "",
            "| Field | Type | Required | Default |",
            "|---|---|---|---|",
        ],
    )
    for field in fields:
        default = _field_default(field)
        lines.append(
            "| {name} | `{type_label}` | {required} | {default} |".format(
                name=_escape_markdown_cell(field.name),
                type_label=_escape_markdown_cell(_type_label(field.type)),
                required="yes" if field.default is msgspec.NODEFAULT and field.default_factory is msgspec.NODEFAULT else "no",
                default=f"`{_escape_markdown_cell(default)}`" if default else "",
            ),
        )
    lines.append("")
    return "\n".join(lines)


def _render_module_doc(module_name: str, structs: list[type[Structure]]) -> str:
    title = f"Structures: `{module_name}`"
    lines = [
        f"# {title}",
        "",
        "<!-- This file is auto-generated by scripts/export_structures.py. -->",
        "<!-- Do not edit manually. -->",
        "",
        f"Total structures: **{len(structs)}**",
        "",
    ]
    for struct_type in structs:
        lines.append(_render_structure_section(struct_type))
    return "\n".join(lines).rstrip() + "\n"


def write_structure_docs(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    modules = _discover_structures()
    written_files: set[str] = set()

    for module_name, structs in modules:
        filename = _module_doc_name(module_name)
        (output_dir / filename).write_text(_render_module_doc(module_name, structs), encoding="utf-8")
        written_files.add(filename)

    index_lines = [
        "# Structures Reference",
        "",
        "<!-- This file is auto-generated by scripts/export_structures.py. -->",
        "<!-- Do not edit manually. -->",
        "",
        "This directory is generated from the `structures` package.",
        "",
        "## Modules",
        "",
    ]
    for module_name, structs in modules:
        filename = _module_doc_name(module_name)
        index_lines.append(f"- [`{module_name}`]({filename}) ({len(structs)} structures)")
    index_lines.append("")
    (output_dir / "README.md").write_text("\n".join(index_lines), encoding="utf-8")
    written_files.add("README.md")

    for existing in output_dir.glob("*.md"):
        if existing.name not in written_files:
            existing.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Xenage structure release manifest for GUI/runtime.")
    parser.add_argument(
        "--out",
        default="apps/xenage-gui/src/generated/control-plane-release.json",
        help="Where to write the generated release manifest.",
    )
    parser.add_argument(
        "--out-ts",
        default="apps/xenage-gui/src/generated/controlPlaneSchema.ts",
        help="Where to write the generated TypeScript manifest module.",
    )
    parser.add_argument(
        "--out-structures-docs",
        default="docs/structures",
        help="Directory where auto-generated structure Markdown docs are written.",
    )
    parser.add_argument(
        "--skip-structures-docs",
        action="store_true",
        help="Skip generating Markdown docs for structures.",
    )
    args = parser.parse_args()

    output_path = Path(args.out)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_ts_path = Path(args.out_ts)

    payload = build_release_manifest()
    encoded = msgspec.json.format(msgspec.json.encode(payload), indent=2)
    output_path.write_bytes(encoded + b"\n")
    write_ts_manifest_module(payload, output_ts_path)

    if not args.skip_structures_docs:
        write_structure_docs(Path(args.out_structures_docs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
