apiVersion: xenage.io/v1alpha1
kind: ClusterConnection
metadata:
  name: demo-admin
spec:
  clusterName: demo
  controlPlaneUrls:
    - http://127.0.0.1:8734
    - http://127.0.0.1:18734
    - http://127.0.0.1:28734
  user:
    id: admin
    role: admin
    publicKey: REPLACE_WITH_GENERATED_PUBLIC_KEY
    privateKey: REPLACE_WITH_GENERATED_PRIVATE_KEY
